[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perp_amm = "brriXKXk4fveoRhSSVPdxJPjNoSEEjRyR7i5mGbFD1D"
perp_margin_accounts = "brrFTzk9JScspG4H1sqthrQHnJoBBg9BA8v31Bn8V3R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
ammtest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/amm-*.ts"
margintest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/margin-*.ts"
